"""Modified Products Table

Revision ID: e4c579154218
Revises: ebb609b71541
Create Date: 2023-12-22 18:13:41.918198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4c579154218'
down_revision: Union[str, None] = 'ebb609b71541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('units', sa.Integer(), nullable=False))
    op.add_column('Products', sa.Column('in_stock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'in_stock')
    op.drop_column('Products', 'units')
    # ### end Alembic commands ###
