"""Changed Product Table

Revision ID: e9fcbc2664c4
Revises: b8d2d2d356d1
Create Date: 2023-12-26 12:24:57.929212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9fcbc2664c4'
down_revision: Union[str, None] = 'b8d2d2d356d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
