"""Created Product and Cart Tables

Revision ID: ebb609b71541
Revises: 972853f74b20
Create Date: 2023-12-22 18:05:59.520291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb609b71541'
down_revision: Union[str, None] = '972853f74b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('ProductID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProductName', sa.String(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('ProductID')
    )
    op.create_table('cart',
    sa.Column('CartID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('ProductID', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('CartID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    op.drop_table('Products')
    # ### end Alembic commands ###
