"""Remove Product Image Table and added ImageURL

Revision ID: 277baa61edbd
Revises: c806d7fc221d
Create Date: 2024-02-28 21:19:24.924212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277baa61edbd'
down_revision: Union[str, None] = 'c806d7fc221d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('ImageURL', sa.String(), nullable=False))
    op.drop_column('Products', 'ImageID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('ImageID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Products', 'ImageURL')
    # ### end Alembic commands ###
