"""Dropped User Id

Revision ID: 5f6c4dcb1558
Revises: 70d06d9fbf3f
Create Date: 2024-01-07 18:47:22.846642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6c4dcb1558'
down_revision: Union[str, None] = '70d06d9fbf3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint('cart_UserID_fkey', 'cart', type_='foreignkey')
    op.drop_column('Users', 'id')
    op.drop_column('cart', 'UserID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('UserID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cart_UserID_fkey', 'cart', 'Users', ['UserID'], ['id'])
    op.add_column('Users', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
