"""Modified Foreign Key for Address and orders

Revision ID: 8836b89a9a2f
Revises: e063b8d0fed5
Create Date: 2024-02-27 08:35:33.410443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8836b89a9a2f'
down_revision: Union[str, None] = 'e063b8d0fed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'UserID',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'UserID',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
