"""Initiate Database

Revision ID: b8d2d2d356d1
Revises: 
Create Date: 2023-12-26 12:21:15.417453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d2d2d356d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductsImages',
    sa.Column('ImageID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('ImageID')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Products',
    sa.Column('ProductID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProductName', sa.String(), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.Column('Price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('ImageID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ImageID'], ['ProductsImages.ImageID'], ),
    sa.PrimaryKeyConstraint('ProductID')
    )
    op.create_table('cart',
    sa.Column('CartID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('ProductID', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('CartID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    op.drop_table('Products')
    op.drop_table('Users')
    op.drop_table('ProductsImages')
    # ### end Alembic commands ###
